
#+private
package gpu

import vk "vendor:vulkan"

// This is generated by meta.odin. DO NOT MODIFY MANUALLY.

LAYERS :: [dynamic; 8]Layer

Layer :: struct #all_or_none
{
    init: proc(validation := true, loc := #caller_location)->(bool),
    cleanup: proc(loc := #caller_location),
    wait_idle: proc(),
    swapchain_create: proc(surface: vk.SurfaceKHR, init_size: []u32, frames_in_flight: u32, present_mode: Present_Mode = {}),
    swapchain_resize: proc(size: []u32),
    swapchain_acquire_next: proc(loc := #caller_location)->(Texture),
    swapchain_present: proc(queue: Queue, sem_wait: Semaphore, wait_value: u64, loc := #caller_location),
    features_available: proc()->(Features),
    device_limits: proc()->(Device_Limits),
    mem_alloc_raw: proc(el_size, el_count, align: i64, mem_type := Memory.Default, loc := #caller_location)->(ptr),
    mem_suballoc: proc(addr: ptr, offset, el_size, el_count: i64, loc := #caller_location)->(ptr),
    mem_free_raw: proc(addr: gpuptr, loc := #caller_location),
    texture_size_and_align: proc(desc: Texture_Desc, loc := #caller_location)->(size: u64, align: u64),
    texture_create: proc(desc: Texture_Desc, storage: gpuptr, queue: Queue = nil, signal_sem: Semaphore = {}, signal_value: u64 = 0, name := "", loc := #caller_location)->(Texture),
    texture_destroy: proc(texture: Texture, loc := #caller_location),
    desc_heap_create: proc(texture_count: u32 = 65536, texture_rw_count: u32 = 65536, sampler_count: u32 = 32, bvh_count: u32 = 16, name := "", loc := #caller_location)->(Descriptor_Heap),
    desc_heap_destroy: proc(heap: Descriptor_Heap, loc := #caller_location),
    desc_heap_set_textures: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location),
    desc_heap_set_textures_rw: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location),
    desc_heap_set_samplers: proc(heap: Descriptor_Heap, start_idx: u32, samplers: []Sampler_Descriptor, loc := #caller_location),
    desc_heap_set_bvhs: proc(heap: Descriptor_Heap, start_idx: u32, bvhs: []BVH, loc := #caller_location),
    texture_view_descriptor: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location)->(Texture_Descriptor),
    texture_rw_view_descriptor: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location)->(Texture_Descriptor),
    sampler_descriptor: proc(sampler_desc: Sampler_Desc, loc := #caller_location)->(Sampler_Descriptor),
    shader_create: proc(code: []u32, type: Shader_Type_Graphics, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location)->(Shader),
    shader_create_compute: proc(code: []u32, group_size_x: u32, group_size_y: u32 = 1, group_size_z: u32 = 1, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location)->(Shader),
    shader_destroy: proc(shader: Shader, loc := #caller_location),
    semaphore_create: proc(init_value: u64 = 0, name := "", loc := #caller_location)->(Semaphore),
    semaphore_get_value: proc(sem: Semaphore, loc := #caller_location)->(u64),
    semaphore_wait: proc(sem: Semaphore, wait_value: u64, loc := #caller_location),
    semaphore_destroy: proc(sem: Semaphore, loc := #caller_location),
    queue_wait_idle: proc(queue: Queue),
    queue_submit: proc(queue: Queue, cmd_bufs: []Command_Buffer, loc := #caller_location),
    blas_size_and_align: proc(desc: BLAS_Desc, loc := #caller_location)->(size: u64, align: u64),
    blas_create: proc(desc: BLAS_Desc, storage: gpuptr, name := "", loc := #caller_location)->(BVH),
    blas_build_scratch_buffer_size_and_align: proc(desc: BLAS_Desc, loc := #caller_location)->(size: u64, align: u64),
    tlas_size_and_align: proc(desc: TLAS_Desc, loc := #caller_location)->(size: u64, align: u64),
    tlas_create: proc(desc: TLAS_Desc, storage: gpuptr, name := "", loc := #caller_location)->(BVH),
    tlas_build_scratch_buffer_size_and_align: proc(desc: TLAS_Desc, loc := #caller_location)->(size: u64, align: u64),
    bvh_root_ptr: proc(bvh: BVH, loc := #caller_location)->(rawptr),
    bvh_destroy: proc(bvh: BVH, loc := #caller_location),
    commands_begin: proc(queue: Queue, loc := #caller_location)->(Command_Buffer),
    cmd_mem_copy_raw: proc(cmd_buf: Command_Buffer, dst, src: gpuptr, bytes: i64, loc := #caller_location),
    cmd_copy_to_texture: proc(cmd_buf: Command_Buffer, dst: Texture, src: gpuptr, region: Texture_Region = {}, loc := #caller_location),
    cmd_copy_from_texture: proc(cmd_buf: Command_Buffer, dst: gpuptr, src: Texture, region: Texture_Region = {}, loc := #caller_location),
    cmd_blit_texture: proc(cmd_buf: Command_Buffer, dst: Texture, dst_rect: Blit_Rect, src: Texture, src_rect: Blit_Rect, filter: Filter, loc := #caller_location),
    cmd_set_desc_heap: proc(cmd_buf: Command_Buffer, heap: Descriptor_Heap, loc := #caller_location),
    cmd_add_wait_semaphore: proc(cmd_buf: Command_Buffer, sem: Semaphore, wait_value: u64, loc := #caller_location),
    cmd_add_signal_semaphore: proc(cmd_buf: Command_Buffer, sem: Semaphore, signal_value: u64, loc := #caller_location),
    cmd_barrier: proc(cmd_buf: Command_Buffer, before: Stage, after: Stage, hazards: Hazard_Flags = {}, loc := #caller_location),
    cmd_set_shaders: proc(cmd_buf: Command_Buffer, vert_shader: Shader, frag_shader: Shader, loc := #caller_location),
    cmd_set_compute_shader: proc(cmd_buf: Command_Buffer, compute_shader: Shader, loc := #caller_location),
    cmd_set_depth_state: proc(cmd_buf: Command_Buffer, state: Depth_State, loc := #caller_location),
    cmd_set_raster_state: proc(cmd_buf: Command_Buffer, state: Raster_State, loc := #caller_location),
    cmd_set_blend_state: proc(cmd_buf: Command_Buffer, state: Blend_State, loc := #caller_location),
    cmd_set_viewport: proc(cmd_buf: Command_Buffer, viewport: Viewport, loc := #caller_location),
    cmd_set_scissor: proc(cmd_buf: Command_Buffer, scissor: Rect_2D, loc := #caller_location),
    cmd_dispatch: proc(cmd_buf: Command_Buffer, compute_data: gpuptr, num_groups_x: u32, num_groups_y: u32 = 1, num_groups_z: u32 = 1, loc := #caller_location),
    cmd_dispatch_indirect_raw: proc(cmd_buf: Command_Buffer, compute_data, arguments: gpuptr, loc := #caller_location),
    cmd_begin_render_pass: proc(cmd_buf: Command_Buffer, desc: Render_Pass_Desc, loc := #caller_location),
    cmd_end_render_pass: proc(cmd_buf: Command_Buffer, loc := #caller_location),
    cmd_draw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data: gpuptr, vertex_count: u32, instance_count: u32 = 1, loc := #caller_location),
    cmd_draw_indexed_raw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, index_count: u32, instance_count: u32 = 1, loc := #caller_location),
    cmd_draw_indexed_indirect_raw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, loc := #caller_location),
    cmd_draw_indexed_indirect_multi_raw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, stride: u32, draw_count: gpuptr, loc := #caller_location),
    cmd_build_blas: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, shapes: []BVH_Shape, loc := #caller_location),
    cmd_build_tlas: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, instances: gpuptr, loc := #caller_location),
    cmd_begin_debug_label: proc(cmd_buf: Command_Buffer, name: string, color: []f32, loc := #caller_location),
    cmd_end_debug_label: proc(cmd_buf: Command_Buffer, loc := #caller_location),
    cmd_insert_debug_label: proc(cmd_buf: Command_Buffer, name: string, color: []f32, loc := #caller_location),
}

_init_meta :: proc(validation := true, loc := #caller_location)->(bool)
{ return {} }
_cleanup_meta :: proc(loc := #caller_location)
{ }
_wait_idle_meta :: proc()
{ }
_swapchain_create_meta :: proc(surface: vk.SurfaceKHR, init_size: []u32, frames_in_flight: u32, present_mode: Present_Mode = {})
{ }
_swapchain_resize_meta :: proc(size: []u32)
{ }
_swapchain_acquire_next_meta :: proc(loc := #caller_location)->(Texture)
{ return {} }
_swapchain_present_meta :: proc(queue: Queue, sem_wait: Semaphore, wait_value: u64, loc := #caller_location)
{ }
_features_available_meta :: proc()->(Features)
{ return {} }
_device_limits_meta :: proc()->(Device_Limits)
{ return {} }
_mem_alloc_raw_meta :: proc(el_size, el_count, align: i64, mem_type := Memory.Default, loc := #caller_location)->(ptr)
{ return {} }
_mem_suballoc_meta :: proc(addr: ptr, offset, el_size, el_count: i64, loc := #caller_location)->(ptr)
{ return {} }
_mem_free_raw_meta :: proc(addr: gpuptr, loc := #caller_location)
{ }
_texture_size_and_align_meta :: proc(desc: Texture_Desc, loc := #caller_location)->(size: u64, align: u64)
{ return {}, {} }
_texture_create_meta :: proc(desc: Texture_Desc, storage: gpuptr, queue: Queue = nil, signal_sem: Semaphore = {}, signal_value: u64 = 0, name := "", loc := #caller_location)->(Texture)
{ return {} }
_texture_destroy_meta :: proc(texture: Texture, loc := #caller_location)
{ }
_desc_heap_create_meta :: proc(texture_count: u32 = 65536, texture_rw_count: u32 = 65536, sampler_count: u32 = 32, bvh_count: u32 = 16, name := "", loc := #caller_location)->(Descriptor_Heap)
{ return {} }
_desc_heap_destroy_meta :: proc(heap: Descriptor_Heap, loc := #caller_location)
{ }
_desc_heap_set_textures_meta :: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location)
{ }
_desc_heap_set_textures_rw_meta :: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location)
{ }
_desc_heap_set_samplers_meta :: proc(heap: Descriptor_Heap, start_idx: u32, samplers: []Sampler_Descriptor, loc := #caller_location)
{ }
_desc_heap_set_bvhs_meta :: proc(heap: Descriptor_Heap, start_idx: u32, bvhs: []BVH, loc := #caller_location)
{ }
_texture_view_descriptor_meta :: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location)->(Texture_Descriptor)
{ return {} }
_texture_rw_view_descriptor_meta :: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location)->(Texture_Descriptor)
{ return {} }
_sampler_descriptor_meta :: proc(sampler_desc: Sampler_Desc, loc := #caller_location)->(Sampler_Descriptor)
{ return {} }
_shader_create_meta :: proc(code: []u32, type: Shader_Type_Graphics, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location)->(Shader)
{ return {} }
_shader_create_compute_meta :: proc(code: []u32, group_size_x: u32, group_size_y: u32 = 1, group_size_z: u32 = 1, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location)->(Shader)
{ return {} }
_shader_destroy_meta :: proc(shader: Shader, loc := #caller_location)
{ }
_semaphore_create_meta :: proc(init_value: u64 = 0, name := "", loc := #caller_location)->(Semaphore)
{ return {} }
_semaphore_get_value_meta :: proc(sem: Semaphore, loc := #caller_location)->(u64)
{ return {} }
_semaphore_wait_meta :: proc(sem: Semaphore, wait_value: u64, loc := #caller_location)
{ }
_semaphore_destroy_meta :: proc(sem: Semaphore, loc := #caller_location)
{ }
_queue_wait_idle_meta :: proc(queue: Queue)
{ }
_queue_submit_meta :: proc(queue: Queue, cmd_bufs: []Command_Buffer, loc := #caller_location)
{ }
_blas_size_and_align_meta :: proc(desc: BLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{ return {}, {} }
_blas_create_meta :: proc(desc: BLAS_Desc, storage: gpuptr, name := "", loc := #caller_location)->(BVH)
{ return {} }
_blas_build_scratch_buffer_size_and_align_meta :: proc(desc: BLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{ return {}, {} }
_tlas_size_and_align_meta :: proc(desc: TLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{ return {}, {} }
_tlas_create_meta :: proc(desc: TLAS_Desc, storage: gpuptr, name := "", loc := #caller_location)->(BVH)
{ return {} }
_tlas_build_scratch_buffer_size_and_align_meta :: proc(desc: TLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{ return {}, {} }
_bvh_root_ptr_meta :: proc(bvh: BVH, loc := #caller_location)->(rawptr)
{ return {} }
_bvh_destroy_meta :: proc(bvh: BVH, loc := #caller_location)
{ }
_commands_begin_meta :: proc(queue: Queue, loc := #caller_location)->(Command_Buffer)
{ return {} }
_cmd_mem_copy_raw_meta :: proc(cmd_buf: Command_Buffer, dst, src: gpuptr, bytes: i64, loc := #caller_location)
{ }
_cmd_copy_to_texture_meta :: proc(cmd_buf: Command_Buffer, dst: Texture, src: gpuptr, region: Texture_Region = {}, loc := #caller_location)
{ }
_cmd_copy_from_texture_meta :: proc(cmd_buf: Command_Buffer, dst: gpuptr, src: Texture, region: Texture_Region = {}, loc := #caller_location)
{ }
_cmd_blit_texture_meta :: proc(cmd_buf: Command_Buffer, dst: Texture, dst_rect: Blit_Rect, src: Texture, src_rect: Blit_Rect, filter: Filter, loc := #caller_location)
{ }
_cmd_set_desc_heap_meta :: proc(cmd_buf: Command_Buffer, heap: Descriptor_Heap, loc := #caller_location)
{ }
_cmd_add_wait_semaphore_meta :: proc(cmd_buf: Command_Buffer, sem: Semaphore, wait_value: u64, loc := #caller_location)
{ }
_cmd_add_signal_semaphore_meta :: proc(cmd_buf: Command_Buffer, sem: Semaphore, signal_value: u64, loc := #caller_location)
{ }
_cmd_barrier_meta :: proc(cmd_buf: Command_Buffer, before: Stage, after: Stage, hazards: Hazard_Flags = {}, loc := #caller_location)
{ }
_cmd_set_shaders_meta :: proc(cmd_buf: Command_Buffer, vert_shader: Shader, frag_shader: Shader, loc := #caller_location)
{ }
_cmd_set_compute_shader_meta :: proc(cmd_buf: Command_Buffer, compute_shader: Shader, loc := #caller_location)
{ }
_cmd_set_depth_state_meta :: proc(cmd_buf: Command_Buffer, state: Depth_State, loc := #caller_location)
{ }
_cmd_set_raster_state_meta :: proc(cmd_buf: Command_Buffer, state: Raster_State, loc := #caller_location)
{ }
_cmd_set_blend_state_meta :: proc(cmd_buf: Command_Buffer, state: Blend_State, loc := #caller_location)
{ }
_cmd_set_viewport_meta :: proc(cmd_buf: Command_Buffer, viewport: Viewport, loc := #caller_location)
{ }
_cmd_set_scissor_meta :: proc(cmd_buf: Command_Buffer, scissor: Rect_2D, loc := #caller_location)
{ }
_cmd_dispatch_meta :: proc(cmd_buf: Command_Buffer, compute_data: gpuptr, num_groups_x: u32, num_groups_y: u32 = 1, num_groups_z: u32 = 1, loc := #caller_location)
{ }
_cmd_dispatch_indirect_raw_meta :: proc(cmd_buf: Command_Buffer, compute_data, arguments: gpuptr, loc := #caller_location)
{ }
_cmd_begin_render_pass_meta :: proc(cmd_buf: Command_Buffer, desc: Render_Pass_Desc, loc := #caller_location)
{ }
_cmd_end_render_pass_meta :: proc(cmd_buf: Command_Buffer, loc := #caller_location)
{ }
_cmd_draw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data: gpuptr, vertex_count: u32, instance_count: u32 = 1, loc := #caller_location)
{ }
_cmd_draw_indexed_raw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, index_count: u32, instance_count: u32 = 1, loc := #caller_location)
{ }
_cmd_draw_indexed_indirect_raw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, loc := #caller_location)
{ }
_cmd_draw_indexed_indirect_multi_raw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, stride: u32, draw_count: gpuptr, loc := #caller_location)
{ }
_cmd_build_blas_meta :: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, shapes: []BVH_Shape, loc := #caller_location)
{ }
_cmd_build_tlas_meta :: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, instances: gpuptr, loc := #caller_location)
{ }
_cmd_begin_debug_label_meta :: proc(cmd_buf: Command_Buffer, name: string, color: []f32, loc := #caller_location)
{ }
_cmd_end_debug_label_meta :: proc(cmd_buf: Command_Buffer, loc := #caller_location)
{ }
_cmd_insert_debug_label_meta :: proc(cmd_buf: Command_Buffer, name: string, color: []f32, loc := #caller_location)
{ }
