
//#+private
package gpu

import intr "base:intrinsics"
import vk "vendor:vulkan"

// This is generated by meta.odin. DO NOT MODIFY MANUALLY.

LAYERS: [dynamic; 8]Layer

// Each proc returns a bool which decides whether to proceed with the next layers (and lib call) or not.
@(private)
Layer :: struct //#all_or_none
{
    init: proc(validation := true, debugging := false, loc := #caller_location) -> bool,
    cleanup: proc(loc := #caller_location) -> bool,
    wait_idle: proc() -> bool,
    swapchain_create: proc(surface: vk.SurfaceKHR, init_size: [2]u32, frames_in_flight: u32, present_mode: Present_Mode = {}) -> bool,
    swapchain_resize: proc(size: [2]u32) -> bool,
    swapchain_acquire_next: proc(loc := #caller_location) -> bool,
    swapchain_present: proc(queue: Queue, sem_wait: Semaphore, wait_value: u64, loc := #caller_location) -> bool,
    features_available: proc() -> bool,
    device_limits: proc() -> bool,
    mem_alloc_raw: proc(#any_int el_size, #any_int el_count, #any_int align: i64, mem_type := Memory.Default, loc := #caller_location) -> bool,
    mem_suballoc: proc(addr: ptr, offset, el_size, el_count: i64, loc := #caller_location) -> bool,
    mem_free_raw: proc(addr: gpuptr, loc := #caller_location) -> bool,
    texture_size_and_align: proc(desc: Texture_Desc, loc := #caller_location) -> bool,
    texture_create: proc(desc: Texture_Desc, storage: gpuptr, queue: Queue = nil, signal_sem: Semaphore = {}, signal_value: u64 = 0, name := "", loc := #caller_location) -> bool,
    texture_destroy: proc(texture: Texture, loc := #caller_location) -> bool,
    desc_heap_create: proc(texture_count: u32 = 65536, texture_rw_count: u32 = 65536, sampler_count: u32 = 32, bvh_count: u32 = 16, name := "", loc := #caller_location) -> bool,
    desc_heap_destroy: proc(heap: Descriptor_Heap, loc := #caller_location) -> bool,
    desc_heap_set_textures: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location) -> bool,
    desc_heap_set_textures_rw: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location) -> bool,
    desc_heap_set_samplers: proc(heap: Descriptor_Heap, start_idx: u32, samplers: []Sampler_Descriptor, loc := #caller_location) -> bool,
    desc_heap_set_bvhs: proc(heap: Descriptor_Heap, start_idx: u32, bvhs: []BVH, loc := #caller_location) -> bool,
    texture_view_descriptor: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location) -> bool,
    texture_rw_view_descriptor: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location) -> bool,
    sampler_descriptor: proc(sampler_desc: Sampler_Desc, loc := #caller_location) -> bool,
    shader_create: proc(code: []u32, type: Shader_Type_Graphics, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location) -> bool,
    shader_create_compute: proc(code: []u32, group_size_x: u32, group_size_y: u32 = 1, group_size_z: u32 = 1, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location) -> bool,
    shader_destroy: proc(shader: Shader, loc := #caller_location) -> bool,
    semaphore_create: proc(init_value: u64 = 0, name := "", loc := #caller_location) -> bool,
    semaphore_get_value: proc(sem: Semaphore, loc := #caller_location) -> bool,
    semaphore_wait: proc(sem: Semaphore, wait_value: u64, loc := #caller_location) -> bool,
    semaphore_destroy: proc(sem: Semaphore, loc := #caller_location) -> bool,
    queue_wait_idle: proc(queue: Queue) -> bool,
    queue_submit: proc(queue: Queue, cmd_bufs: []Command_Buffer, loc := #caller_location) -> bool,
    blas_size_and_align: proc(desc: BLAS_Desc, loc := #caller_location) -> bool,
    blas_create: proc(desc: BLAS_Desc, storage: gpuptr, name := "", loc := #caller_location) -> bool,
    blas_build_scratch_buffer_size_and_align: proc(desc: BLAS_Desc, loc := #caller_location) -> bool,
    tlas_size_and_align: proc(desc: TLAS_Desc, loc := #caller_location) -> bool,
    tlas_create: proc(desc: TLAS_Desc, storage: gpuptr, name := "", loc := #caller_location) -> bool,
    tlas_build_scratch_buffer_size_and_align: proc(desc: TLAS_Desc, loc := #caller_location) -> bool,
    bvh_root_ptr: proc(bvh: BVH, loc := #caller_location) -> bool,
    bvh_destroy: proc(bvh: BVH, loc := #caller_location) -> bool,
    commands_begin: proc(queue: Queue, loc := #caller_location) -> bool,
    cmd_mem_copy_raw: proc(cmd_buf: Command_Buffer, dst, src: gpuptr, #any_int bytes: i64, loc := #caller_location) -> bool,
    cmd_copy_to_texture: proc(cmd_buf: Command_Buffer, dst: Texture, src: gpuptr, region: Texture_Region = {}, loc := #caller_location) -> bool,
    cmd_copy_from_texture: proc(cmd_buf: Command_Buffer, dst: gpuptr, src: Texture, region: Texture_Region = {}, loc := #caller_location) -> bool,
    cmd_blit_texture: proc(cmd_buf: Command_Buffer, dst: Texture, dst_rect: Blit_Rect, src: Texture, src_rect: Blit_Rect, filter: Filter, loc := #caller_location) -> bool,
    cmd_set_desc_heap: proc(cmd_buf: Command_Buffer, heap: Descriptor_Heap, loc := #caller_location) -> bool,
    cmd_add_wait_semaphore: proc(cmd_buf: Command_Buffer, sem: Semaphore, wait_value: u64, loc := #caller_location) -> bool,
    cmd_add_signal_semaphore: proc(cmd_buf: Command_Buffer, sem: Semaphore, signal_value: u64, loc := #caller_location) -> bool,
    cmd_barrier: proc(cmd_buf: Command_Buffer, before: Stage, after: Stage, hazards: Hazard_Flags = {}, loc := #caller_location) -> bool,
    cmd_set_shaders: proc(cmd_buf: Command_Buffer, vert_shader: Shader, frag_shader: Shader, loc := #caller_location) -> bool,
    cmd_set_compute_shader: proc(cmd_buf: Command_Buffer, compute_shader: Shader, loc := #caller_location) -> bool,
    cmd_set_depth_state: proc(cmd_buf: Command_Buffer, state: Depth_State, loc := #caller_location) -> bool,
    cmd_set_raster_state: proc(cmd_buf: Command_Buffer, state: Raster_State, loc := #caller_location) -> bool,
    cmd_set_blend_state: proc(cmd_buf: Command_Buffer, state: Blend_State, loc := #caller_location) -> bool,
    cmd_set_viewport: proc(cmd_buf: Command_Buffer, viewport: Viewport, loc := #caller_location) -> bool,
    cmd_set_scissor: proc(cmd_buf: Command_Buffer, scissor: Rect_2D, loc := #caller_location) -> bool,
    cmd_dispatch: proc(cmd_buf: Command_Buffer, compute_data: gpuptr, num_groups_x: u32, num_groups_y: u32 = 1, num_groups_z: u32 = 1, loc := #caller_location) -> bool,
    cmd_dispatch_indirect_raw: proc(cmd_buf: Command_Buffer, compute_data, arguments: gpuptr, loc := #caller_location) -> bool,
    cmd_begin_render_pass: proc(cmd_buf: Command_Buffer, desc: Render_Pass_Desc, loc := #caller_location) -> bool,
    cmd_end_render_pass: proc(cmd_buf: Command_Buffer, loc := #caller_location) -> bool,
    cmd_draw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data: gpuptr, vertex_count: u32, instance_count: u32 = 1, loc := #caller_location) -> bool,
    cmd_draw_indexed_raw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, index_count: u32, instance_count: u32 = 1, loc := #caller_location) -> bool,
    cmd_draw_indexed_indirect_raw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, loc := #caller_location) -> bool,
    cmd_draw_indexed_indirect_multi_raw: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, stride: u32, draw_count: gpuptr, loc := #caller_location) -> bool,
    cmd_build_blas: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, shapes: []BVH_Shape, loc := #caller_location) -> bool,
    cmd_build_tlas: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, instances: gpuptr, loc := #caller_location) -> bool,
    cmd_begin_debug_label: proc(cmd_buf: Command_Buffer, name: string, color: [4]f32, loc := #caller_location) -> bool,
    cmd_end_debug_label: proc(cmd_buf: Command_Buffer, loc := #caller_location) -> bool,
    cmd_insert_debug_label: proc(cmd_buf: Command_Buffer, name: string, color: [4]f32, loc := #caller_location) -> bool,
    debug_record_begin: proc(loc := #caller_location) -> bool,
    debug_record_end: proc(loc := #caller_location) -> bool,
}

_init_meta :: proc(validation := true, debugging := false, loc := #caller_location)->(bool)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.init != nil {
                if !layer.init(validation, debugging, loc) do return {}
            }
        }
    }
    return #force_inline _init(validation, debugging, loc)
}

_cleanup_meta :: proc(loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cleanup != nil {
                if !layer.cleanup(loc) do return 
            }
        }
    }
    #force_inline _cleanup(loc)
}

_wait_idle_meta :: proc()
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.wait_idle != nil {
                if !layer.wait_idle() do return 
            }
        }
    }
    #force_inline _wait_idle()
}

_swapchain_create_meta :: proc(surface: vk.SurfaceKHR, init_size: [2]u32, frames_in_flight: u32, present_mode: Present_Mode = {})
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.swapchain_create != nil {
                if !layer.swapchain_create(surface, init_size, frames_in_flight, present_mode) do return 
            }
        }
    }
    #force_inline _swapchain_create(surface, init_size, frames_in_flight, present_mode)
}

_swapchain_resize_meta :: proc(size: [2]u32)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.swapchain_resize != nil {
                if !layer.swapchain_resize(size) do return 
            }
        }
    }
    #force_inline _swapchain_resize(size)
}

_swapchain_acquire_next_meta :: proc(loc := #caller_location)->(Texture)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.swapchain_acquire_next != nil {
                if !layer.swapchain_acquire_next(loc) do return {}
            }
        }
    }
    return #force_inline _swapchain_acquire_next(loc)
}

_swapchain_present_meta :: proc(queue: Queue, sem_wait: Semaphore, wait_value: u64, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.swapchain_present != nil {
                if !layer.swapchain_present(queue, sem_wait, wait_value, loc) do return 
            }
        }
    }
    #force_inline _swapchain_present(queue, sem_wait, wait_value, loc)
}

_features_available_meta :: proc()->(Features)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.features_available != nil {
                if !layer.features_available() do return {}
            }
        }
    }
    return #force_inline _features_available()
}

_device_limits_meta :: proc()->(Device_Limits)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.device_limits != nil {
                if !layer.device_limits() do return {}
            }
        }
    }
    return #force_inline _device_limits()
}

_mem_alloc_raw_meta :: proc(#any_int el_size, #any_int el_count, #any_int align: i64, mem_type := Memory.Default, loc := #caller_location)->(ptr)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.mem_alloc_raw != nil {
                if !layer.mem_alloc_raw(el_size, el_count, align, mem_type, loc) do return {}
            }
        }
    }
    return #force_inline _mem_alloc_raw(el_size, el_count, align, mem_type, loc)
}

_mem_suballoc_meta :: proc(addr: ptr, offset, el_size, el_count: i64, loc := #caller_location)->(ptr)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.mem_suballoc != nil {
                if !layer.mem_suballoc(addr, offset, el_size, el_count, loc) do return {}
            }
        }
    }
    return #force_inline _mem_suballoc(addr, offset, el_size, el_count, loc)
}

_mem_free_raw_meta :: proc(addr: gpuptr, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.mem_free_raw != nil {
                if !layer.mem_free_raw(addr, loc) do return 
            }
        }
    }
    #force_inline _mem_free_raw(addr, loc)
}

_texture_size_and_align_meta :: proc(desc: Texture_Desc, loc := #caller_location)->(size: u64, align: u64)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.texture_size_and_align != nil {
                if !layer.texture_size_and_align(desc, loc) do return {}, {}
            }
        }
    }
    return #force_inline _texture_size_and_align(desc, loc)
}

_texture_create_meta :: proc(desc: Texture_Desc, storage: gpuptr, queue: Queue = nil, signal_sem: Semaphore = {}, signal_value: u64 = 0, name := "", loc := #caller_location)->(Texture)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.texture_create != nil {
                if !layer.texture_create(desc, storage, queue, signal_sem, signal_value, name, loc) do return {}
            }
        }
    }
    return #force_inline _texture_create(desc, storage, queue, signal_sem, signal_value, name, loc)
}

_texture_destroy_meta :: proc(texture: Texture, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.texture_destroy != nil {
                if !layer.texture_destroy(texture, loc) do return 
            }
        }
    }
    #force_inline _texture_destroy(texture, loc)
}

_desc_heap_create_meta :: proc(texture_count: u32 = 65536, texture_rw_count: u32 = 65536, sampler_count: u32 = 32, bvh_count: u32 = 16, name := "", loc := #caller_location)->(Descriptor_Heap)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.desc_heap_create != nil {
                if !layer.desc_heap_create(texture_count, texture_rw_count, sampler_count, bvh_count, name, loc) do return {}
            }
        }
    }
    return #force_inline _desc_heap_create(texture_count, texture_rw_count, sampler_count, bvh_count, name, loc)
}

_desc_heap_destroy_meta :: proc(heap: Descriptor_Heap, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.desc_heap_destroy != nil {
                if !layer.desc_heap_destroy(heap, loc) do return 
            }
        }
    }
    #force_inline _desc_heap_destroy(heap, loc)
}

_desc_heap_set_textures_meta :: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.desc_heap_set_textures != nil {
                if !layer.desc_heap_set_textures(heap, start_idx, textures, loc) do return 
            }
        }
    }
    #force_inline _desc_heap_set_textures(heap, start_idx, textures, loc)
}

_desc_heap_set_textures_rw_meta :: proc(heap: Descriptor_Heap, start_idx: u32, textures: []Texture_Descriptor, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.desc_heap_set_textures_rw != nil {
                if !layer.desc_heap_set_textures_rw(heap, start_idx, textures, loc) do return 
            }
        }
    }
    #force_inline _desc_heap_set_textures_rw(heap, start_idx, textures, loc)
}

_desc_heap_set_samplers_meta :: proc(heap: Descriptor_Heap, start_idx: u32, samplers: []Sampler_Descriptor, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.desc_heap_set_samplers != nil {
                if !layer.desc_heap_set_samplers(heap, start_idx, samplers, loc) do return 
            }
        }
    }
    #force_inline _desc_heap_set_samplers(heap, start_idx, samplers, loc)
}

_desc_heap_set_bvhs_meta :: proc(heap: Descriptor_Heap, start_idx: u32, bvhs: []BVH, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.desc_heap_set_bvhs != nil {
                if !layer.desc_heap_set_bvhs(heap, start_idx, bvhs, loc) do return 
            }
        }
    }
    #force_inline _desc_heap_set_bvhs(heap, start_idx, bvhs, loc)
}

_texture_view_descriptor_meta :: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location)->(Texture_Descriptor)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.texture_view_descriptor != nil {
                if !layer.texture_view_descriptor(texture, view_desc, loc) do return {}
            }
        }
    }
    return #force_inline _texture_view_descriptor(texture, view_desc, loc)
}

_texture_rw_view_descriptor_meta :: proc(texture: Texture, view_desc: Texture_View_Desc, loc := #caller_location)->(Texture_Descriptor)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.texture_rw_view_descriptor != nil {
                if !layer.texture_rw_view_descriptor(texture, view_desc, loc) do return {}
            }
        }
    }
    return #force_inline _texture_rw_view_descriptor(texture, view_desc, loc)
}

_sampler_descriptor_meta :: proc(sampler_desc: Sampler_Desc, loc := #caller_location)->(Sampler_Descriptor)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.sampler_descriptor != nil {
                if !layer.sampler_descriptor(sampler_desc, loc) do return {}
            }
        }
    }
    return #force_inline _sampler_descriptor(sampler_desc, loc)
}

_shader_create_meta :: proc(code: []u32, type: Shader_Type_Graphics, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location)->(Shader)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.shader_create != nil {
                if !layer.shader_create(code, type, entry_point_name, name, spec_constants, loc) do return {}
            }
        }
    }
    return #force_inline _shader_create(code, type, entry_point_name, name, spec_constants, loc)
}

_shader_create_compute_meta :: proc(code: []u32, group_size_x: u32, group_size_y: u32 = 1, group_size_z: u32 = 1, entry_point_name := "main", name := "", spec_constants: []Spec_Constant = {}, loc := #caller_location)->(Shader)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.shader_create_compute != nil {
                if !layer.shader_create_compute(code, group_size_x, group_size_y, group_size_z, entry_point_name, name, spec_constants, loc) do return {}
            }
        }
    }
    return #force_inline _shader_create_compute(code, group_size_x, group_size_y, group_size_z, entry_point_name, name, spec_constants, loc)
}

_shader_destroy_meta :: proc(shader: Shader, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.shader_destroy != nil {
                if !layer.shader_destroy(shader, loc) do return 
            }
        }
    }
    #force_inline _shader_destroy(shader, loc)
}

_semaphore_create_meta :: proc(init_value: u64 = 0, name := "", loc := #caller_location)->(Semaphore)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.semaphore_create != nil {
                if !layer.semaphore_create(init_value, name, loc) do return {}
            }
        }
    }
    return #force_inline _semaphore_create(init_value, name, loc)
}

_semaphore_get_value_meta :: proc(sem: Semaphore, loc := #caller_location)->(u64)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.semaphore_get_value != nil {
                if !layer.semaphore_get_value(sem, loc) do return {}
            }
        }
    }
    return #force_inline _semaphore_get_value(sem, loc)
}

_semaphore_wait_meta :: proc(sem: Semaphore, wait_value: u64, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.semaphore_wait != nil {
                if !layer.semaphore_wait(sem, wait_value, loc) do return 
            }
        }
    }
    #force_inline _semaphore_wait(sem, wait_value, loc)
}

_semaphore_destroy_meta :: proc(sem: Semaphore, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.semaphore_destroy != nil {
                if !layer.semaphore_destroy(sem, loc) do return 
            }
        }
    }
    #force_inline _semaphore_destroy(sem, loc)
}

_queue_wait_idle_meta :: proc(queue: Queue)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.queue_wait_idle != nil {
                if !layer.queue_wait_idle(queue) do return 
            }
        }
    }
    #force_inline _queue_wait_idle(queue)
}

_queue_submit_meta :: proc(queue: Queue, cmd_bufs: []Command_Buffer, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.queue_submit != nil {
                if !layer.queue_submit(queue, cmd_bufs, loc) do return 
            }
        }
    }
    #force_inline _queue_submit(queue, cmd_bufs, loc)
}

_blas_size_and_align_meta :: proc(desc: BLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.blas_size_and_align != nil {
                if !layer.blas_size_and_align(desc, loc) do return {}, {}
            }
        }
    }
    return #force_inline _blas_size_and_align(desc, loc)
}

_blas_create_meta :: proc(desc: BLAS_Desc, storage: gpuptr, name := "", loc := #caller_location)->(BVH)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.blas_create != nil {
                if !layer.blas_create(desc, storage, name, loc) do return {}
            }
        }
    }
    return #force_inline _blas_create(desc, storage, name, loc)
}

_blas_build_scratch_buffer_size_and_align_meta :: proc(desc: BLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.blas_build_scratch_buffer_size_and_align != nil {
                if !layer.blas_build_scratch_buffer_size_and_align(desc, loc) do return {}, {}
            }
        }
    }
    return #force_inline _blas_build_scratch_buffer_size_and_align(desc, loc)
}

_tlas_size_and_align_meta :: proc(desc: TLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.tlas_size_and_align != nil {
                if !layer.tlas_size_and_align(desc, loc) do return {}, {}
            }
        }
    }
    return #force_inline _tlas_size_and_align(desc, loc)
}

_tlas_create_meta :: proc(desc: TLAS_Desc, storage: gpuptr, name := "", loc := #caller_location)->(BVH)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.tlas_create != nil {
                if !layer.tlas_create(desc, storage, name, loc) do return {}
            }
        }
    }
    return #force_inline _tlas_create(desc, storage, name, loc)
}

_tlas_build_scratch_buffer_size_and_align_meta :: proc(desc: TLAS_Desc, loc := #caller_location)->(size: u64, align: u64)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.tlas_build_scratch_buffer_size_and_align != nil {
                if !layer.tlas_build_scratch_buffer_size_and_align(desc, loc) do return {}, {}
            }
        }
    }
    return #force_inline _tlas_build_scratch_buffer_size_and_align(desc, loc)
}

_bvh_root_ptr_meta :: proc(bvh: BVH, loc := #caller_location)->(rawptr)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.bvh_root_ptr != nil {
                if !layer.bvh_root_ptr(bvh, loc) do return {}
            }
        }
    }
    return #force_inline _bvh_root_ptr(bvh, loc)
}

_bvh_destroy_meta :: proc(bvh: BVH, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.bvh_destroy != nil {
                if !layer.bvh_destroy(bvh, loc) do return 
            }
        }
    }
    #force_inline _bvh_destroy(bvh, loc)
}

_commands_begin_meta :: proc(queue: Queue, loc := #caller_location)->(Command_Buffer)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.commands_begin != nil {
                if !layer.commands_begin(queue, loc) do return {}
            }
        }
    }
    return #force_inline _commands_begin(queue, loc)
}

_cmd_mem_copy_raw_meta :: proc(cmd_buf: Command_Buffer, dst, src: gpuptr, #any_int bytes: i64, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_mem_copy_raw != nil {
                if !layer.cmd_mem_copy_raw(cmd_buf, dst, src, bytes, loc) do return 
            }
        }
    }
    #force_inline _cmd_mem_copy_raw(cmd_buf, dst, src, bytes, loc)
}

_cmd_copy_to_texture_meta :: proc(cmd_buf: Command_Buffer, dst: Texture, src: gpuptr, region: Texture_Region = {}, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_copy_to_texture != nil {
                if !layer.cmd_copy_to_texture(cmd_buf, dst, src, region, loc) do return 
            }
        }
    }
    #force_inline _cmd_copy_to_texture(cmd_buf, dst, src, region, loc)
}

_cmd_copy_from_texture_meta :: proc(cmd_buf: Command_Buffer, dst: gpuptr, src: Texture, region: Texture_Region = {}, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_copy_from_texture != nil {
                if !layer.cmd_copy_from_texture(cmd_buf, dst, src, region, loc) do return 
            }
        }
    }
    #force_inline _cmd_copy_from_texture(cmd_buf, dst, src, region, loc)
}

_cmd_blit_texture_meta :: proc(cmd_buf: Command_Buffer, dst: Texture, dst_rect: Blit_Rect, src: Texture, src_rect: Blit_Rect, filter: Filter, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_blit_texture != nil {
                if !layer.cmd_blit_texture(cmd_buf, dst, dst_rect, src, src_rect, filter, loc) do return 
            }
        }
    }
    #force_inline _cmd_blit_texture(cmd_buf, dst, dst_rect, src, src_rect, filter, loc)
}

_cmd_set_desc_heap_meta :: proc(cmd_buf: Command_Buffer, heap: Descriptor_Heap, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_desc_heap != nil {
                if !layer.cmd_set_desc_heap(cmd_buf, heap, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_desc_heap(cmd_buf, heap, loc)
}

_cmd_add_wait_semaphore_meta :: proc(cmd_buf: Command_Buffer, sem: Semaphore, wait_value: u64, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_add_wait_semaphore != nil {
                if !layer.cmd_add_wait_semaphore(cmd_buf, sem, wait_value, loc) do return 
            }
        }
    }
    #force_inline _cmd_add_wait_semaphore(cmd_buf, sem, wait_value, loc)
}

_cmd_add_signal_semaphore_meta :: proc(cmd_buf: Command_Buffer, sem: Semaphore, signal_value: u64, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_add_signal_semaphore != nil {
                if !layer.cmd_add_signal_semaphore(cmd_buf, sem, signal_value, loc) do return 
            }
        }
    }
    #force_inline _cmd_add_signal_semaphore(cmd_buf, sem, signal_value, loc)
}

_cmd_barrier_meta :: proc(cmd_buf: Command_Buffer, before: Stage, after: Stage, hazards: Hazard_Flags = {}, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_barrier != nil {
                if !layer.cmd_barrier(cmd_buf, before, after, hazards, loc) do return 
            }
        }
    }
    #force_inline _cmd_barrier(cmd_buf, before, after, hazards, loc)
}

_cmd_set_shaders_meta :: proc(cmd_buf: Command_Buffer, vert_shader: Shader, frag_shader: Shader, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_shaders != nil {
                if !layer.cmd_set_shaders(cmd_buf, vert_shader, frag_shader, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_shaders(cmd_buf, vert_shader, frag_shader, loc)
}

_cmd_set_compute_shader_meta :: proc(cmd_buf: Command_Buffer, compute_shader: Shader, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_compute_shader != nil {
                if !layer.cmd_set_compute_shader(cmd_buf, compute_shader, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_compute_shader(cmd_buf, compute_shader, loc)
}

_cmd_set_depth_state_meta :: proc(cmd_buf: Command_Buffer, state: Depth_State, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_depth_state != nil {
                if !layer.cmd_set_depth_state(cmd_buf, state, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_depth_state(cmd_buf, state, loc)
}

_cmd_set_raster_state_meta :: proc(cmd_buf: Command_Buffer, state: Raster_State, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_raster_state != nil {
                if !layer.cmd_set_raster_state(cmd_buf, state, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_raster_state(cmd_buf, state, loc)
}

_cmd_set_blend_state_meta :: proc(cmd_buf: Command_Buffer, state: Blend_State, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_blend_state != nil {
                if !layer.cmd_set_blend_state(cmd_buf, state, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_blend_state(cmd_buf, state, loc)
}

_cmd_set_viewport_meta :: proc(cmd_buf: Command_Buffer, viewport: Viewport, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_viewport != nil {
                if !layer.cmd_set_viewport(cmd_buf, viewport, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_viewport(cmd_buf, viewport, loc)
}

_cmd_set_scissor_meta :: proc(cmd_buf: Command_Buffer, scissor: Rect_2D, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_set_scissor != nil {
                if !layer.cmd_set_scissor(cmd_buf, scissor, loc) do return 
            }
        }
    }
    #force_inline _cmd_set_scissor(cmd_buf, scissor, loc)
}

_cmd_dispatch_meta :: proc(cmd_buf: Command_Buffer, compute_data: gpuptr, num_groups_x: u32, num_groups_y: u32 = 1, num_groups_z: u32 = 1, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_dispatch != nil {
                if !layer.cmd_dispatch(cmd_buf, compute_data, num_groups_x, num_groups_y, num_groups_z, loc) do return 
            }
        }
    }
    #force_inline _cmd_dispatch(cmd_buf, compute_data, num_groups_x, num_groups_y, num_groups_z, loc)
}

_cmd_dispatch_indirect_raw_meta :: proc(cmd_buf: Command_Buffer, compute_data, arguments: gpuptr, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_dispatch_indirect_raw != nil {
                if !layer.cmd_dispatch_indirect_raw(cmd_buf, compute_data, arguments, loc) do return 
            }
        }
    }
    #force_inline _cmd_dispatch_indirect_raw(cmd_buf, compute_data, arguments, loc)
}

_cmd_begin_render_pass_meta :: proc(cmd_buf: Command_Buffer, desc: Render_Pass_Desc, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_begin_render_pass != nil {
                if !layer.cmd_begin_render_pass(cmd_buf, desc, loc) do return 
            }
        }
    }
    #force_inline _cmd_begin_render_pass(cmd_buf, desc, loc)
}

_cmd_end_render_pass_meta :: proc(cmd_buf: Command_Buffer, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_end_render_pass != nil {
                if !layer.cmd_end_render_pass(cmd_buf, loc) do return 
            }
        }
    }
    #force_inline _cmd_end_render_pass(cmd_buf, loc)
}

_cmd_draw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data: gpuptr, vertex_count: u32, instance_count: u32 = 1, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_draw != nil {
                if !layer.cmd_draw(cmd_buf, vertex_data, fragment_data, vertex_count, instance_count, loc) do return 
            }
        }
    }
    #force_inline _cmd_draw(cmd_buf, vertex_data, fragment_data, vertex_count, instance_count, loc)
}

_cmd_draw_indexed_raw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, index_count: u32, instance_count: u32 = 1, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_draw_indexed_raw != nil {
                if !layer.cmd_draw_indexed_raw(cmd_buf, vertex_data, fragment_data, indices, index_format, index_count, instance_count, loc) do return 
            }
        }
    }
    #force_inline _cmd_draw_indexed_raw(cmd_buf, vertex_data, fragment_data, indices, index_format, index_count, instance_count, loc)
}

_cmd_draw_indexed_indirect_raw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_draw_indexed_indirect_raw != nil {
                if !layer.cmd_draw_indexed_indirect_raw(cmd_buf, vertex_data, fragment_data, indices, index_format, indirect_arguments, loc) do return 
            }
        }
    }
    #force_inline _cmd_draw_indexed_indirect_raw(cmd_buf, vertex_data, fragment_data, indices, index_format, indirect_arguments, loc)
}

_cmd_draw_indexed_indirect_multi_raw_meta :: proc(cmd_buf: Command_Buffer, vertex_data, fragment_data, indices: gpuptr, index_format: Index_Format, indirect_arguments: gpuptr, stride: u32, draw_count: gpuptr, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_draw_indexed_indirect_multi_raw != nil {
                if !layer.cmd_draw_indexed_indirect_multi_raw(cmd_buf, vertex_data, fragment_data, indices, index_format, indirect_arguments, stride, draw_count, loc) do return 
            }
        }
    }
    #force_inline _cmd_draw_indexed_indirect_multi_raw(cmd_buf, vertex_data, fragment_data, indices, index_format, indirect_arguments, stride, draw_count, loc)
}

_cmd_build_blas_meta :: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, shapes: []BVH_Shape, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_build_blas != nil {
                if !layer.cmd_build_blas(cmd_buf, bvh, scratch_storage, shapes, loc) do return 
            }
        }
    }
    #force_inline _cmd_build_blas(cmd_buf, bvh, scratch_storage, shapes, loc)
}

_cmd_build_tlas_meta :: proc(cmd_buf: Command_Buffer, bvh: BVH, scratch_storage: gpuptr, instances: gpuptr, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_build_tlas != nil {
                if !layer.cmd_build_tlas(cmd_buf, bvh, scratch_storage, instances, loc) do return 
            }
        }
    }
    #force_inline _cmd_build_tlas(cmd_buf, bvh, scratch_storage, instances, loc)
}

_cmd_begin_debug_label_meta :: proc(cmd_buf: Command_Buffer, name: string, color: [4]f32, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_begin_debug_label != nil {
                if !layer.cmd_begin_debug_label(cmd_buf, name, color, loc) do return 
            }
        }
    }
    #force_inline _cmd_begin_debug_label(cmd_buf, name, color, loc)
}

_cmd_end_debug_label_meta :: proc(cmd_buf: Command_Buffer, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_end_debug_label != nil {
                if !layer.cmd_end_debug_label(cmd_buf, loc) do return 
            }
        }
    }
    #force_inline _cmd_end_debug_label(cmd_buf, loc)
}

_cmd_insert_debug_label_meta :: proc(cmd_buf: Command_Buffer, name: string, color: [4]f32, loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.cmd_insert_debug_label != nil {
                if !layer.cmd_insert_debug_label(cmd_buf, name, color, loc) do return 
            }
        }
    }
    #force_inline _cmd_insert_debug_label(cmd_buf, name, color, loc)
}

_debug_record_begin_meta :: proc(loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.debug_record_begin != nil {
                if !layer.debug_record_begin(loc) do return 
            }
        }
    }
    #force_inline _debug_record_begin(loc)
}

_debug_record_end_meta :: proc(loc := #caller_location)
{
    if intr.unlikely(len(LAYERS) > 0) {
        for layer in LAYERS {
            if layer.debug_record_end != nil {
                if !layer.debug_record_end(loc) do return 
            }
        }
    }
    #force_inline _debug_record_end(loc)
}


@(private)
Lib_Proc_ID :: enum
{
    init,
    cleanup,
    wait_idle,
    swapchain_create,
    swapchain_resize,
    swapchain_acquire_next,
    swapchain_present,
    features_available,
    device_limits,
    mem_alloc_raw,
    mem_suballoc,
    mem_free_raw,
    texture_size_and_align,
    texture_create,
    texture_destroy,
    desc_heap_create,
    desc_heap_destroy,
    desc_heap_set_textures,
    desc_heap_set_textures_rw,
    desc_heap_set_samplers,
    desc_heap_set_bvhs,
    texture_view_descriptor,
    texture_rw_view_descriptor,
    sampler_descriptor,
    shader_create,
    shader_create_compute,
    shader_destroy,
    semaphore_create,
    semaphore_get_value,
    semaphore_wait,
    semaphore_destroy,
    queue_wait_idle,
    queue_submit,
    blas_size_and_align,
    blas_create,
    blas_build_scratch_buffer_size_and_align,
    tlas_size_and_align,
    tlas_create,
    tlas_build_scratch_buffer_size_and_align,
    bvh_root_ptr,
    bvh_destroy,
    commands_begin,
    cmd_mem_copy_raw,
    cmd_copy_to_texture,
    cmd_copy_from_texture,
    cmd_blit_texture,
    cmd_set_desc_heap,
    cmd_add_wait_semaphore,
    cmd_add_signal_semaphore,
    cmd_barrier,
    cmd_set_shaders,
    cmd_set_compute_shader,
    cmd_set_depth_state,
    cmd_set_raster_state,
    cmd_set_blend_state,
    cmd_set_viewport,
    cmd_set_scissor,
    cmd_dispatch,
    cmd_dispatch_indirect_raw,
    cmd_begin_render_pass,
    cmd_end_render_pass,
    cmd_draw,
    cmd_draw_indexed_raw,
    cmd_draw_indexed_indirect_raw,
    cmd_draw_indexed_indirect_multi_raw,
    cmd_build_blas,
    cmd_build_tlas,
    cmd_begin_debug_label,
    cmd_end_debug_label,
    cmd_insert_debug_label,
    debug_record_begin,
    debug_record_end,
}
