
package meta

import "core:fmt"
import "core:os"
import "core:odin/ast"
import "core:odin/parser"
import str "core:strings"
import "core:reflect"

main :: proc()
{
    if len(os.args) != 2 {
        fmt.eprintln("usage: meta <source_path.odin> <dst_path.odin>")
        return
    }

    src_path := os.args[1]
    dst_path := os.args[2]
    generate_code(src_path, dst_path)
}

generate_code :: proc(source_path: string, dst_path: string) -> bool
{
    data, err := os.read_entire_file(source_path, allocator = context.allocator)
    if err != nil
    {
        fmt.eprintln("failed to read file:", err)
        return false
    }
    defer delete(data)

    file := ast.File {
        fullpath = source_path,
        src      = string(data),
    }

    p := parser.default_parser()

    if !parser.parse_file(&p, &file)
    {
        fmt.eprintln("Failed to parse:", source_path)
        return false
    }

    sb := str.builder_make_none()
    defer str.builder_destroy(&sb)

    str.write_string(&sb, PREAMBLE)

    write_layer_struct(&sb, file)
    fmt.sbprintln(&sb, "")
    write_meta_procs(&sb, file)

    err_w := os.write_entire_file(dst_path, str.to_string(sb))
    ensure(err_w == nil)

    return true
}

PREAMBLE ::
`
//#+private
package gpu

import intr "base:intrinsics"
import vk "vendor:vulkan"

// This is generated by meta.odin. DO NOT MODIFY MANUALLY.

LAYERS: [dynamic; 8]Layer

`

write_meta_procs :: proc(sb: ^str.Builder, file: ast.File)
{
    for stmt in file.decls
    {
        decl := stmt.derived_stmt.(^ast.Value_Decl) or_continue
        if decl.type == nil do continue
        proc_type := decl.type.derived_expr.(^ast.Proc_Type) or_continue

        if len(decl.names) <= 0 do continue
        name := decl.names[0]
        ident := name.derived_expr.(^ast.Ident) or_continue
        fmt.sbprintf(sb, "_%s_meta :: proc(", ident.name)
        write_proc_fields(sb, proc_type.params.list)
        fmt.sbprint(sb, ")")
        if proc_type.results != nil && len(proc_type.results.list) > 0
        {
            fmt.sbprintf(sb, "->(")
            write_proc_fields(sb, proc_type.results.list)
            fmt.sbprintf(sb, ")")
        }
        fmt.sbprintln(sb, "")
        fmt.sbprintln(sb, "{")

        // Preamble, run layers
        fmt.sbprintln (sb, "    if intr.unlikely(len(LAYERS) > 0) {")
        fmt.sbprintln (sb, "        for layer in LAYERS {")
        fmt.sbprintfln(sb, "            if layer.%s != nil {{", ident.name)
        fmt.sbprintf  (sb, "                if !layer.%s(", ident.name)
        write_proc_fields(sb, proc_type.params.list, names_only = true)
        fmt.sbprint   (sb, ") do return ")
        first_res := true
        if proc_type.results != nil do for _ in proc_type.results.list {
            if !first_res do fmt.sbprint(sb, ", ")
            fmt.sbprint(sb, "{}")
            first_res = false
        }
        fmt.sbprintln (sb, "")
        fmt.sbprintln (sb, "            }")
        fmt.sbprintln (sb, "        }")
        fmt.sbprintln (sb, "    }")

        if proc_type.results != nil && len(proc_type.results.list) > 0 {
            fmt.sbprint(sb, "    return ")
        } else {
            fmt.sbprint(sb, "    ")
        }
        fmt.sbprintf (sb, "#force_inline _%s(", ident.name)
        write_proc_fields(sb, proc_type.params.list, names_only = true)
        fmt.sbprintln(sb, ")")
        fmt.sbprintln(sb, "}")
        fmt.sbprintln(sb, "")
    }
}

write_layer_struct :: proc(sb: ^str.Builder, file: ast.File)
{
    fmt.sbprintln (sb, "// Each proc returns a bool which decides whether to proceed with the lib call or not.")
    fmt.sbprintln (sb, "@(private)")
    fmt.sbprintfln(sb, "Layer :: struct //#all_or_none")
    fmt.sbprintln (sb, "{")
    for stmt in file.decls
    {
        decl := stmt.derived_stmt.(^ast.Value_Decl) or_continue
        if decl.type == nil do continue
        proc_type := decl.type.derived_expr.(^ast.Proc_Type) or_continue

        if len(decl.names) <= 0 do continue
        name := decl.names[0]
        ident := name.derived_expr.(^ast.Ident) or_continue
        fmt.sbprintf(sb, "    %s: proc(", ident.name)
        write_proc_fields(sb, proc_type.params.list)
        fmt.sbprintfln(sb, ") -> bool,")
    }
    fmt.sbprintln(sb, "}")
}

write_proc_fields :: proc(sb: ^str.Builder, fields: []^ast.Field, names_only := false)
{
    first_param := true
    for param in fields
    {
        if !first_param {
            fmt.sbprintf(sb, ", ")
        }

        first_name := true
        for param_expr in param.names
        {
            param_ident := param_expr.derived_expr.(^ast.Ident) or_continue
            if !first_name {
                fmt.sbprintf(sb, ", ")
            }

            if !names_only {
                if .Any_Int in param.flags {
                    fmt.sbprint(sb, "#any_int ")
                }
            }

            fmt.sbprintf(sb, "%s", param_ident.name)
            first_name = false
        }

        if !names_only
        {
            if param.type == nil && param.default_value == nil do continue

            if len(param.names) > 0
            {
                if param.type == nil {
                    fmt.sbprintf(sb, " :")
                } else {
                    fmt.sbprintf(sb, ": ")
                }
            }

            if param.type != nil
            {
                write_type(sb, param.type)
                if param.default_value != nil {
                    fmt.sbprintf(sb, " ")
                }
            }

            if param.default_value != nil {
                fmt.sbprintf(sb, "= ")
                write_value(sb, param.default_value)
            }
        }

        first_param = false
    }
}

write_type :: proc(sb: ^str.Builder, type: ^ast.Expr)
{
    #partial switch type in type.derived_expr
    {
        case ^ast.Pointer_Type:
        {
            fmt.sbprint(sb, "^")
            write_type(sb, type.elem)
        }
        case ^ast.Array_Type:
        {
            fmt.sbprint(sb, "[")
            if type.len != nil {
                write_value(sb, type.len)
            }
            fmt.sbprint(sb, "]")
            write_type(sb, type.elem)
        }
        case ^ast.Ident:
        {
            fmt.sbprint(sb, type.name)
        }
        case ^ast.Selector_Expr:
        {
            write_type(sb, type.expr)
            fmt.sbprint(sb, ".")
            fmt.sbprint(sb, type.field.name)
        }
        case:
        {
            fmt.sbprintf(sb, "<unknown type of type: %t>", reflect.union_variant_typeid(type))
        }
    }
}

write_value :: proc(sb: ^str.Builder, type: ^ast.Expr)
{
    #partial switch value in type.derived_expr
    {
        case ^ast.Basic_Lit:
        {
            fmt.sbprint(sb, value.tok.text)
        }
        case ^ast.Ident:
        {
            fmt.sbprint(sb, value.name)
        }
        case ^ast.Basic_Directive:
        {
            fmt.sbprintf(sb, "#%s", value.name)
        }
        case ^ast.Comp_Lit:
        {
            fmt.sbprint(sb, "{")
            is_first_elem := true
            for elem in value.elems
            {
                if !is_first_elem do fmt.sbprint(sb, ", ")
                write_value(sb, elem)
                is_first_elem = false
            }
            fmt.sbprint(sb, "}")
        }
        case ^ast.Selector_Expr:
        {
            write_type(sb, value.expr)
            fmt.sbprint(sb, ".")
            fmt.sbprint(sb, value.field.name)
        }
        case:
        {
            fmt.sbprintf(sb, "<unknown value of type: %t>", reflect.union_variant_typeid(value))
        }
    }
}
