
package meta

import "core:fmt"
import "core:os"
import "core:odin/ast"
import "core:odin/parser"
import str "core:strings"

main :: proc()
{
    if len(os.args) != 2 {
        fmt.eprintln("usage: meta <source_path.odin> <dst_path.odin>")
        return
    }

    src_path := os.args[1]
    dst_path := os.args[2]
    generate_code(src_path, dst_path)
}

generate_code :: proc(source_path: string, dst_path: string)
{
    data, err := os.read_entire_file(source_path, allocator = context.allocator)
    if err != nil
    {
        fmt.eprintln("failed to read file:", err)
        return
    }
    defer delete(data)

    file := ast.File {
        fullpath = source_path,
        src      = string(data),
    }

    p := parser.default_parser()

    if !parser.parse_file(&p, &file)
    {
        fmt.eprintln("Failed to parse:", source_path)
        return
    }

    sb := str.builder_make_none()
    defer str.builder_destroy(&sb)

    str.write_string(&sb, PREAMBLE)

    write_layer_struct(&sb, file)
    fmt.sbprintln(&sb, "")
    write_meta_procs(&sb, file)

    fmt.println(str.to_string(sb))
}

PREAMBLE :: `

package gpu

// This is generated by meta.odin. DO NOT MODIFY MANUALLY.

`

write_meta_procs :: proc(sb: ^str.Builder, file: ast.File)
{
    for stmt in file.decls
    {
        decl := stmt.derived_stmt.(^ast.Value_Decl) or_continue
        if decl.type == nil do continue
        proc_type := decl.type.derived_expr.(^ast.Proc_Type) or_continue

        if len(decl.names) <= 0 do continue
        name := decl.names[0]
        ident := name.derived_expr.(^ast.Ident) or_continue
        fmt.sbprintf(sb, "_%s_meta :: (", ident.name)
        write_proc_fields(sb, proc_type.params.list)
        fmt.sbprintln(sb, ") {}")
    }
}

write_layer_struct :: proc(sb: ^str.Builder, file: ast.File)
{
    fmt.sbprintfln(sb, "Layer :: struct #all_or_none")
    fmt.sbprintln(sb, "{")
    for stmt in file.decls
    {
        decl := stmt.derived_stmt.(^ast.Value_Decl) or_continue
        if decl.type == nil do continue
        proc_type := decl.type.derived_expr.(^ast.Proc_Type) or_continue

        if len(decl.names) <= 0 do continue
        name := decl.names[0]
        ident := name.derived_expr.(^ast.Ident) or_continue
        fmt.sbprintf(sb, "    %s: ^proc(", ident.name)
        write_proc_fields(sb, proc_type.params.list)
        fmt.sbprintf(sb, ")->")
        fmt.sbprintln(sb, "")
    }
    fmt.sbprintln(sb, "}")
}

write_proc_fields :: proc(sb: ^str.Builder, fields: []^ast.Field)
{
    for param in fields
    {
        first_name := true
        for param_expr in param.names
        {
            param_ident := param_expr.derived_expr.(^ast.Ident) or_continue
            if !first_name {
                fmt.sbprintf(sb, ", ")
            }
            fmt.sbprintf(sb, "%s", param_ident.name)
            first_name = false
        }

        fmt.sbprintf(sb, ": some_type, ")
    }
}
