name: Generate Goldens

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Odin
        uses: laytan/setup-odin@v2
        with:
          release: dev-2026-06
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: 1.4.350.0
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true

          #install_swiftshader: true
          install_lavapipe: true
      - name: Run Tests
        #env:
        #  VK_ICD_FILENAMES: C:\lavapipe\share\vulkan\icd.d\lvp_icd.x86_64.json
        run: odin run tests/no_gfx
      #- run: ./render_tests --output golden-images/
      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: golden-images
      #    path: golden-images