name: Generate Goldens

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: laytan/setup-odin@v2
        with:
          release: dev-2026-06
      - run: odin run ../../tests/no_gfx
      #- run: ./render_tests --output golden-images/
      #- uses: actions/upload-artifact@v4
      #  with:
      #    name: golden-images
      #    path: golden-images